{
 "title": "Nucleus Admin Dashboard",
 "tags": [
  "nucleus",
  "admin"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"nucleus-system\", container=\"nucleus-admin\"}[5m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"nucleus-system\", container=\"nucleus-admin\"})",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{namespace=\"nucleus-system\", service=\"nucleus-admin\"}[5m]))",
     "legendFormat": "HTTP Requests"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_http_request_duration_seconds_bucket{namespace=\"nucleus-system\", service=\"nucleus-admin\"}[5m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_request_duration_seconds_bucket{namespace=\"nucleus-system\", service=\"nucleus-admin\"}[5m])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  }
 ]
}