apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- registry-secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: nucleus-admin
  app.kubernetes.io/part-of: nucleus-platform
  app.kubernetes.io/managed-by: kustomize
