apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: nucleus-system
type: kubernetes.io/dockerconfigjson
data:
  # docker login 정보를 base64로 인코딩한 값
  # 다음 명령으로 생성: kubectl create secret docker-registry registry-credentials --docker-server=<your-registry> --docker-username=<username> --docker-password=<password> --docker-email=<email> -o yaml --dry-run=client
  .dockerconfigjson: eHh4eA==  # 실제 값으로 대체 필요
