apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: nucleus-system

commonLabels:
  environment: staging

patchesStrategicMerge:
- configmap.yaml

images:
- name: your-private-registry.example.com/nucleus-admin
  newTag: staging
